"""create initial tables

Revision ID: 94e7db9b206e
Revises:
Create Date: 2026-02-17 20:51:12.736558

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "94e7db9b206e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "extraction_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("opinion_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="queued", nullable=False),
        sa.Column("total_opinions", sa.Integer(), nullable=False),
        sa.Column("processed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("failed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_extraction_jobs_status"), "extraction_jobs", ["status"], unique=False)
    op.create_table(
        "opinions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("courtlistener_id", sa.Integer(), nullable=False),
        sa.Column("court_id", sa.String(length=50), nullable=False),
        sa.Column("court_level", sa.String(length=30), nullable=False),
        sa.Column("case_name", sa.Text(), nullable=False),
        sa.Column("date_filed", sa.Date(), nullable=False),
        sa.Column("precedential_status", sa.String(length=30), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("citation_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("judges", sa.Text(), server_default="", nullable=False),
        sa.Column("jurisdiction", sa.String(length=50), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_opinions_court_date", "opinions", ["court_id", "date_filed"], unique=False)
    op.create_index(op.f("ix_opinions_court_id"), "opinions", ["court_id"], unique=False)
    op.create_index(
        op.f("ix_opinions_courtlistener_id"), "opinions", ["courtlistener_id"], unique=True
    )
    op.create_index(op.f("ix_opinions_date_filed"), "opinions", ["date_filed"], unique=False)
    op.create_index(op.f("ix_opinions_jurisdiction"), "opinions", ["jurisdiction"], unique=False)
    op.create_table(
        "citations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("citing_opinion_id", sa.Integer(), nullable=False),
        sa.Column("cited_opinion_id", sa.Integer(), nullable=True),
        sa.Column("citation_string", sa.Text(), nullable=False),
        sa.Column("cited_case_name", sa.Text(), nullable=True),
        sa.Column("citation_context", sa.Text(), nullable=False),
        sa.Column("citation_type", sa.String(length=20), nullable=False),
        sa.Column("paragraph_context", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["cited_opinion_id"], ["opinions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["citing_opinion_id"], ["opinions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_citations_cited_opinion_id"), "citations", ["cited_opinion_id"], unique=False
    )
    op.create_index(
        "ix_citations_citing_cited",
        "citations",
        ["citing_opinion_id", "cited_opinion_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_citations_citing_opinion_id"), "citations", ["citing_opinion_id"], unique=False
    )
    op.create_table(
        "conflicts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("opinion_a_id", sa.Integer(), nullable=False),
        sa.Column("opinion_b_id", sa.Integer(), nullable=False),
        sa.Column("topic", sa.Text(), nullable=False),
        sa.Column("court_a", sa.String(length=100), nullable=False),
        sa.Column("court_b", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=20), server_default="detected", nullable=False),
        sa.ForeignKeyConstraint(["opinion_a_id"], ["opinions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["opinion_b_id"], ["opinions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_conflicts_opinion_a_id"), "conflicts", ["opinion_a_id"], unique=False)
    op.create_index(op.f("ix_conflicts_opinion_b_id"), "conflicts", ["opinion_b_id"], unique=False)
    op.create_index(
        "ix_conflicts_opinions", "conflicts", ["opinion_a_id", "opinion_b_id"], unique=True
    )
    op.create_index(op.f("ix_conflicts_status"), "conflicts", ["status"], unique=False)
    op.create_table(
        "extractions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("opinion_id", sa.Integer(), nullable=False),
        sa.Column("holding", sa.Text(), nullable=False),
        sa.Column("holding_confidence", sa.Float(), nullable=False),
        sa.Column("legal_standard", sa.Text(), nullable=True),
        sa.Column("disposition", sa.String(length=30), nullable=False),
        sa.Column("disposition_confidence", sa.Float(), nullable=False),
        sa.Column("dissent_present", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("dissent_summary", sa.Text(), nullable=True),
        sa.Column("concurrence_present", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("concurrence_summary", sa.Text(), nullable=True),
        sa.Column("legal_topics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("extraction_model", sa.String(length=50), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.ForeignKeyConstraint(["opinion_id"], ["opinions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_extractions_opinion_id"), "extractions", ["opinion_id"], unique=False)
    op.create_index(op.f("ix_extractions_status"), "extractions", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_extractions_status"), table_name="extractions")
    op.drop_index(op.f("ix_extractions_opinion_id"), table_name="extractions")
    op.drop_table("extractions")
    op.drop_index(op.f("ix_conflicts_status"), table_name="conflicts")
    op.drop_index("ix_conflicts_opinions", table_name="conflicts")
    op.drop_index(op.f("ix_conflicts_opinion_b_id"), table_name="conflicts")
    op.drop_index(op.f("ix_conflicts_opinion_a_id"), table_name="conflicts")
    op.drop_table("conflicts")
    op.drop_index(op.f("ix_citations_citing_opinion_id"), table_name="citations")
    op.drop_index("ix_citations_citing_cited", table_name="citations")
    op.drop_index(op.f("ix_citations_cited_opinion_id"), table_name="citations")
    op.drop_table("citations")
    op.drop_index(op.f("ix_opinions_jurisdiction"), table_name="opinions")
    op.drop_index(op.f("ix_opinions_date_filed"), table_name="opinions")
    op.drop_index(op.f("ix_opinions_courtlistener_id"), table_name="opinions")
    op.drop_index(op.f("ix_opinions_court_id"), table_name="opinions")
    op.drop_index("ix_opinions_court_date", table_name="opinions")
    op.drop_table("opinions")
    op.drop_index(op.f("ix_extraction_jobs_status"), table_name="extraction_jobs")
    op.drop_table("extraction_jobs")
    # ### end Alembic commands ###
